A maze command
Jo3-L/yagpdb-cc pull request #79
Opened 2020-09-22 23:48 UTC by Crenshaw7860

Generates a maze with an optional amount bridges (path parts you can go under/over) I think it would be a nice addition. I hope you enjoy it.

2020-09-22 23:52 UTC, Crenshaw7860 commented on fun/maze.cc.lau
> +{{else if .ExecData}}
I plan on making this (.ExecData) go away by having a variable set for (index .CmdArgs 0), so I can just have
```
{{$data:=""}}
{{if .ExecData}}
     {{$data = .ExecData}}
{{else}}
     {{$data = (index .CmdArgs 0)}}
{{end}}
```

2020-09-23 02:56 UTC, Jo3-L requested changes
Just a few things to change, otherwise LGTM.

2020-09-23 02:56 UTC, Jo3-L commented on fun/maze.cc.lau
> +It also shows the solution, and works with .ExecData*/}}
This comment is formatted incorrectly. Please refer to the contributing guide for how to format the top comment.

2020-09-23 02:56 UTC, Jo3-L commented on fun/maze.cc.lau
> +     {{$maze:=(joinStr "" "http://maze5.de/cgi-bin/maze?sample=1&type=4&rows=12&columns=12&crossings=" (index .CmdArgs 0) "&seed=" $seed "&algorithm=backtracker&algorithm=0.5&foreground=%23ffffff&bac
You can use `$maze` here instead of `(index .CmdArgs 0)`.

2020-09-23 18:36 UTC, merged

2020-09-23 18:36 UTC, Jo3-L commented
thanks for the PR!