Fix some typos on SuggestionV2's README
Jo3-L/yagpdb-cc pull request #80
Opened 2020-10-03 14:53 UTC by MatiasMFM2001

Some notes:

- In `Configuration Variables -> 4.` I've seen this, but I'm not sure if that's OK:
> This provides a good way to organise all approved suggestions. This provides a good way to organise all implemnted suggestions into a separate channel.

- In `Configuration Variables -> 7. and 8.` I've edited this:
> Supports both custom as well as inbuilt emojis, for which it is recommended...

Is that better than previous redaction?

2020-10-07 05:35 UTC, Satty9361 commented
The emoji one is incorrect. Unicode is only to be used for inbuilt emojis since unicode for custom emojis dont exist. You'd use the full emoji output after escaping it for those.

2020-10-07 06:48 UTC, MatiasMFM2001 commented
Oh

Original:
> The emoji for upvote reaction. Supports both custom as well as inbuilt emojis. For inbuilt emojis, it is recommended to use corresponding unicode characters. Example : "👍".

Edited:
> The emoji for upvote reaction. Supports both custom as well as inbuilt emojis, for which it is recommended to use corresponding unicode characters. Example : "👍".

So, both are incorrect? Anyways, I would add your line (thanks!):
> For custom emojis, you'd use the full emoji output after escaping it for those.

2020-10-08 22:27 UTC, Jo3-L commented
what's the status of this PR currently?

2020-10-08 23:07 UTC, MatiasMFM2001 commented
In my fork, `Configuration Variables -> 4` isn't modified. And `Configuration Variables -> 7. and 8.` is modified, but I'm not sure if it's incorrect (Satty's comment)

I see some changes in your repo were done. Should I sync them with mine?

2020-10-13 22:02 UTC, Jo3-L requested changes
Some nits

2020-10-13 22:02 UTC, Jo3-L commented on suggestion/v2/README.md
> +	The emoji for upvote reaction. Supports both custom as well as inbuilt emojis, for which it is recommended to use corresponding unicode characters. Example : "👍".
This (imo) actually makes the sentence less clear, please revert.

2020-10-13 22:02 UTC, Jo3-L commented on suggestion/v2/README.md
> +	The emoji for downvote reaction. Supports both custom as well as inbuilt emojis, for which it is recommended to use corresponding unicode characters. Example : "👎".
Please revert this according to above comment as well.

2020-10-13 22:11 UTC, merged

2020-10-13 22:11 UTC, Jo3-L commented
thanks, lgtm.

2020-10-13 22:42 UTC, MatiasMFM2001 commented
You're welcome!